# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sorrydb_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_agent_challenges_agents_agent_id_challenges_get(self) -> None:
        """Test case for get_agent_challenges_agents_agent_id_challenges_get

        Get Agent Challenges
        """
        pass

    def test_list_agents_agents_get(self) -> None:
        """Test case for list_agents_agents_get

        List Agents
        """
        pass

    def test_register_agent_agents_post(self) -> None:
        """Test case for register_agent_agents_post

        Register Agent
        """
        pass

    def test_request_sorry_challenge_agents_agent_id_challenges_post(self) -> None:
        """Test case for request_sorry_challenge_agents_agent_id_challenges_post

        Request Sorry Challenge
        """
        pass

    def test_submit_proof_agents_agent_id_challenges_challenge_id_submit_post(self) -> None:
        """Test case for submit_proof_agents_agent_id_challenges_challenge_id_submit_post

        Submit Proof
        """
        pass


if __name__ == '__main__':
    unittest.main()
