# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sorrydb_api_client.models.sorry import Sorry

class TestSorry(unittest.TestCase):
    """Sorry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Sorry:
        """Test Sorry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Sorry`
        """
        model = Sorry()
        if include_optional:
            return Sorry(
                repo = sorrydb_api_client.models.repo_info.RepoInfo(
                    remote = '', 
                    branch = '', 
                    commit = '', 
                    lean_version = '', ),
                location = sorrydb_api_client.models.location.Location(
                    path = '', 
                    start_line = 56, 
                    start_column = 56, 
                    end_line = 56, 
                    end_column = 56, ),
                debug_info = sorrydb_api_client.models.debug_info.DebugInfo(
                    goal = '', 
                    url = '', ),
                metadata = sorrydb_api_client.models.metadata.Metadata(
                    blame_email_hash = '', 
                    blame_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    inclusion_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                id = ''
            )
        else:
            return Sorry(
                repo = sorrydb_api_client.models.repo_info.RepoInfo(
                    remote = '', 
                    branch = '', 
                    commit = '', 
                    lean_version = '', ),
                location = sorrydb_api_client.models.location.Location(
                    path = '', 
                    start_line = 56, 
                    start_column = 56, 
                    end_line = 56, 
                    end_column = 56, ),
                debug_info = sorrydb_api_client.models.debug_info.DebugInfo(
                    goal = '', 
                    url = '', ),
                metadata = sorrydb_api_client.models.metadata.Metadata(
                    blame_email_hash = '', 
                    blame_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    inclusion_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testSorry(self):
        """Test Sorry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
