# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sorrydb_api_client.models.challenge_read import ChallengeRead

class TestChallengeRead(unittest.TestCase):
    """ChallengeRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeRead:
        """Test ChallengeRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChallengeRead`
        """
        model = ChallengeRead()
        if include_optional:
            return ChallengeRead(
                id = '',
                deadline = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sorry = sorrydb_api_client.models.sql_sorry.SQLSorry(
                    id = '', 
                    remote = '', 
                    branch = '', 
                    commit = '', 
                    lean_version = '', 
                    path = '', 
                    start_line = 56, 
                    start_column = 56, 
                    end_line = 56, 
                    end_column = 56, 
                    goal = '', 
                    url = '', 
                    blame_email_hash = '', 
                    blame_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    inclusion_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                status = 'AWAITING_SUBMISSION',
                submission = ''
            )
        else:
            return ChallengeRead(
                id = '',
                deadline = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sorry = sorrydb_api_client.models.sql_sorry.SQLSorry(
                    id = '', 
                    remote = '', 
                    branch = '', 
                    commit = '', 
                    lean_version = '', 
                    path = '', 
                    start_line = 56, 
                    start_column = 56, 
                    end_line = 56, 
                    end_column = 56, 
                    goal = '', 
                    url = '', 
                    blame_email_hash = '', 
                    blame_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    inclusion_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                status = 'AWAITING_SUBMISSION',
                submission = '',
        )
        """

    def testChallengeRead(self):
        """Test ChallengeRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
