# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sorrydb_api_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_change_password_auth_change_password_post(self) -> None:
        """Test case for change_password_auth_change_password_post

        Change Password
        """
        pass

    def test_get_current_user_info_auth_me_get(self) -> None:
        """Test case for get_current_user_info_auth_me_get

        Get Current User Info
        """
        pass

    def test_login_auth_token_post(self) -> None:
        """Test case for login_auth_token_post

        Login
        """
        pass

    def test_register_auth_register_post(self) -> None:
        """Test case for register_auth_register_post

        Register
        """
        pass


if __name__ == '__main__':
    unittest.main()
