# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sorrydb_api_client.models.debug_info import DebugInfo

class TestDebugInfo(unittest.TestCase):
    """DebugInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebugInfo:
        """Test DebugInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebugInfo`
        """
        model = DebugInfo()
        if include_optional:
            return DebugInfo(
                goal = '',
                url = ''
            )
        else:
            return DebugInfo(
                goal = '',
                url = '',
        )
        """

    def testDebugInfo(self):
        """Test DebugInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
