# coding: utf-8

# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AgentCreate",
    "AgentRead",
    "ChallengeRead",
    "ChallengeStatus",
    "ChallengeSubmissionCreate",
    "HTTPValidationError",
    "SQLSorry",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from sorrydb_api_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from sorrydb_api_client.api_response import ApiResponse as ApiResponse
from sorrydb_api_client.api_client import ApiClient as ApiClient
from sorrydb_api_client.configuration import Configuration as Configuration
from sorrydb_api_client.exceptions import OpenApiException as OpenApiException
from sorrydb_api_client.exceptions import ApiTypeError as ApiTypeError
from sorrydb_api_client.exceptions import ApiValueError as ApiValueError
from sorrydb_api_client.exceptions import ApiKeyError as ApiKeyError
from sorrydb_api_client.exceptions import ApiAttributeError as ApiAttributeError
from sorrydb_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from sorrydb_api_client.models.agent_create import AgentCreate as AgentCreate
from sorrydb_api_client.models.agent_read import AgentRead as AgentRead
from sorrydb_api_client.models.challenge_read import ChallengeRead as ChallengeRead
from sorrydb_api_client.models.challenge_status import ChallengeStatus as ChallengeStatus
from sorrydb_api_client.models.challenge_submission_create import ChallengeSubmissionCreate as ChallengeSubmissionCreate
from sorrydb_api_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from sorrydb_api_client.models.sql_sorry import SQLSorry as SQLSorry
from sorrydb_api_client.models.validation_error import ValidationError as ValidationError
from sorrydb_api_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
